# 파일 규격 버전
version: "3.1"

# 실행하려는 컨테이너들 정의
services:
  # 서비스명
  redis:
    # 컨테이너명
    container_name: redis
    # 사용할 이미지
    image: redis:latest
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ./redis/data:/data
    # 컨테이너에 docker label을 이용해서 메타데이터 추가

  green:
    container_name: green
    image: spring-cicd
    ports:
      - "8080:8080"

  blue:
    container_name: blue
    image: spring-cicd
    ports:
      - "8081:8080"